In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
flat=pd.read_csv(r"C:\Users\Vinay Babu\Downloads\flats_uncleaned.csv")

In [4]:
flat.head()

,property_name,areaWithType,square_feet,transaction,status,floor,furnishing,facing,description,price_per_sqft,price
0,2 BHK Apartment for Sale in Dindoli Surat,Carpet Area,644 sqft,New Property,Poss. by Oct '24,5 out of 10,Unfurnished,West,"Luxury project with basement parking, Solar ro...","₹2,891 per sqft",₹33.8 Lac
1,2 BHK Apartment for Sale in Althan Surat,Super Area,1278 sqft,New Property,Poss. by Jan '26,6 out of 14,Unfurnished,South -West,2 And 3 BHK Luxurious Flat for Sell In New Alt...,"₹3,551 per sqft",₹45.4 Lac
2,2 BHK Apartment for Sale in Pal Gam Surat,Super Area,1173 sqft,Resale,Ready to Move,5 out of 13,Semi-Furnished,East,This affordable 2 BHK flat is situated along a...,"₹3,800 per sqft",₹44.6 Lac
3,2 BHK Apartment for Sale in Jahangirabad Surat,Carpet Area,700 sqft,New Property,Ready to Move,6 out of 14,Unfurnished,East,2 BHK Flat For sell IN Jahangirabad Prime Loca...,"₹3,966 per sqft",₹47 Lac
4,"2 BHK Apartment for Sale in Orchid Fantasia, P...",Super Area,1250 sqft,Orchid Fantasia,New Property,Unfurnished,2,2,"Multistorey Apartment for Sale in Palanpur, Su...","₹3,600 per sqft",₹45 Lac

In [5]:
flat['price'].unique()

<StringArray>
['₹33.8 Lac ', '₹45.4 Lac ', '₹44.6 Lac ',   '₹47 Lac ',   '₹45 Lac ',
 '₹43.2 Lac ', '₹42.1 Lac ', '₹44.1 Lac ', '₹44.3 Lac ',   '₹40 Lac ',
 ...
  '₹3.21 Cr ',  '₹4.14 Cr ',  '₹4.41 Cr ',  '₹7.65 Cr ',  '₹5.20 Cr ',
  '₹4.39 Cr ',  '₹4.68 Cr ',  '₹4.67 Cr ',  '₹5.60 Cr ',  '₹6.08 Cr ']
Length: 841, dtype: str

In [6]:
flat['price'].value_counts()

price
Call for Price    173
₹50 Lac           106
₹35 Lac            79
₹1 Cr              74
₹65 Lac            73
                 ...
₹4.39 Cr            1
₹4.68 Cr            1
₹4.67 Cr            1
₹5.60 Cr            1
₹6.08 Cr            1
Name: count, Length: 841, dtype: int64

In [7]:
flat['price'].replace('Call for Price',np.nan)

0       ₹33.8 Lac
1       ₹45.4 Lac
2       ₹44.6 Lac
3         ₹47 Lac
4         ₹45 Lac
           ...
4520           NaN
4521           NaN
4522           NaN
4523           NaN
4524           NaN
Name: price, Length: 4525, dtype: str

In [8]:
flat['price'].unique

<bound method Series.unique of 0           ₹33.8 Lac
1           ₹45.4 Lac
2           ₹44.6 Lac
3             ₹47 Lac
4             ₹45 Lac
             ...
4520    Call for Price
4521    Call for Price
4522    Call for Price
4523    Call for Price
4524    Call for Price
Name: price, Length: 4525, dtype: str>

In [9]:
i='₹4.68 Cr'
i=i.strip('₹ Cr')
float(i)*100000

468000.0

In [10]:
for i in flat['price']:
    out=0
    if 'Lac' in i:
        out.append(float(i.strip('₹ Lac'))*100000)

AttributeError: 'int' object has no attribute 'append'

In [ ]:
df_1=pd.DataFrame(
    {
    'Name':['Ritik','Sameer','Devesh','Rahul'],
    'Eid':[i for i in range(101,105)],
    'Salary':[12000,70000,5000,110000]
}
)
df_1

     Name  Eid  Salary
0   Ritik  101   12000
1  Sameer  102   70000
2  Devesh  103    5000
3   Rahul  104  110000

In [ ]:
df_2=pd.DataFrame({
    'Name':['Mohan','Sohan','Rohan','Tohan'],
    'Eid':[i for i in range(110,114)],
    'Salary':[11000,21000,5500,12000]
})
df_2

    Name  Eid  Salary
0  Mohan  110   11000
1  Sohan  111   21000
2  Rohan  112    5500
3  Tohan  113   12000

In [ ]:
df_3=pd.DataFrame({
    'Blood Group':['A+','B+','o+'],
    'Eid':[105,104,101],
    'Fees':[12000,10000,15000]
})
df_3

  Blood Group  Eid   Fees
0          A+  105  12000
1          B+  104  10000
2          o+  101  15000

In [ ]:
df_1,df_3

(     Name  Eid  Salary
 0   Ritik  101   12000
 1  Sameer  102   70000
 2  Devesh  103    5000
 3   Rahul  104  110000,
   Blood Group  Eid   Fees
 0          A+  105  12000
 1          B+  104  10000
 2          o+  101  15000)

In [ ]:
pd.merge(df_1,df_3,on='Eid',how='inner')  # how many members going to main members

    Name  Eid  Salary Blood Group   Fees
0  Ritik  101   12000          o+  15000
1  Rahul  104  110000          B+  10000

In [ ]:
pd.merge(df_1,df_3,on='Eid',how='outer')  # full join

     Name  Eid    Salary Blood Group     Fees
0   Ritik  101   12000.0          o+  15000.0
1  Sameer  102   70000.0         NaN      NaN
2  Devesh  103    5000.0         NaN      NaN
3   Rahul  104  110000.0          B+  10000.0
4     NaN  105       NaN          A+  12000.0

In [ ]:
pd.merge(df_1,df_3,on='Eid',how='left')

     Name  Eid  Salary Blood Group     Fees
0   Ritik  101   12000          o+  15000.0
1  Sameer  102   70000         NaN      NaN
2  Devesh  103    5000         NaN      NaN
3   Rahul  104  110000          B+  10000.0

In [ ]:
pd.merge(df_1,df_3,on='Eid',how='right')

    Name  Eid    Salary Blood Group   Fees
0    NaN  105       NaN          A+  12000
1  Rahul  104  110000.0          B+  10000
2  Ritik  101   12000.0          o+  15000

feature Engineering:
                    it is a process of creting new coloun besde on exesting colou

titan=pd.read_csv(r"C:\Users\Vinay Babu\Downloads\Data-Analysis-Datasets-main.zip\Data-Analysis-Datasets-main\Datasets-Practice")

In [ ]:
titan=pd.read_csv(r"C:\Users\Vinay Babu\Downloads\Data-Analysis-Datasets-main\Data-Analysis-Datasets-main\Datasets-Practice\titanic.csv")

In [ ]:
titan['family_count_withou']=titan['sibsp']+titan['parch']

In [ ]:
# family count including the family leader.

In [ ]:
titan.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived,family_count_withou
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1,0
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1,3
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0,3
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0,3
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0,3

In [ ]:
titan.columns

Index(['pclass', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket', 'fare',
       'cabin', 'embarked', 'survived', 'family_count_withou'],
      dtype='str')

In [ ]:
titan['family_count_withou']=titan['sibsp']+titan['parch']+1
titan.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived,family_count_withou
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1,4
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0,4
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0,4
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0,4

In [ ]:
# fetch family_name/sur_name
titan['name'].unique()

<StringArray>
[                  'Allen, Miss. Elisabeth Walton',
                  'Allison, Master. Hudson Trevor',
                    'Allison, Miss. Helen Loraine',
            'Allison, Mr. Hudson Joshua Creighton',
 'Allison, Mrs. Hudson J C (Bessie Waldo Daniels)',
                             'Anderson, Mr. Harry',
               'Andrews, Miss. Kornelia Theodosia',
                          'Andrews, Mr. Thomas Jr',
   'Appleton, Mrs. Edward Dale (Charlotte Lamson)',
                         'Artagaveytia, Mr. Ramon',
 ...
                             'Yasbeck, Mr. Antoni',
         'Yasbeck, Mrs. Antoni (Selini Alexander)',
                            'Youseff, Mr. Gerious',
                               'Yousif, Mr. Wazli',
                           'Yousseff, Mr. Gerious',
                            'Zabour, Miss. Hileni',
                           'Zabour, Miss. Thamine',
                       'Zakarian, Mr. Mapriededer',
                             'Zakarian, Mr. Ortin',
                              'Zimmerman, Mr. Leo']
Length: 1307, dtype: str

In [ ]:
sur_name=[]
for i in titan['name']:
    sur_name.append(i.split(',')[0])
titan['sur_name']=sur_name              # surname with loop function

In [ ]:
titan['sur_name']

0           Allen
1         Allison
2         Allison
3         Allison
4         Allison
          ...
1304       Zabour
1305       Zabour
1306     Zakarian
1307     Zakarian
1308    Zimmerman
Name: sur_name, Length: 1309, dtype: str

In [ ]:
titan['family_name_1']=titan['name'].str.split(',').str[0]  # sirf surname print hoga without for loop

In [ ]:
titan['family_name_1']

0           Allen
1         Allison
2         Allison
3         Allison
4         Allison
          ...
1304       Zabour
1305       Zabour
1306     Zakarian
1307     Zakarian
1308    Zimmerman
Name: family_name_1, Length: 1309, dtype: object

In [ ]:
# Fetch the title of the traveller.

In [ ]:
titan['family_name_2']=titan['name'].str.split().str[1]  # without using loop to print title

In [ ]:
titan['family_name_2']

0         Miss.
1       Master.
2         Miss.
3           Mr.
4          Mrs.
         ...
1304      Miss.
1305      Miss.
1306        Mr.
1307        Mr.
1308        Mr.
Name: family_name_2, Length: 1309, dtype: object

In [ ]:
title=[]
for i in titan['name']:
    title.append(i.split()[1])
titan['title']=title            # using for loop print to title.

In [ ]:
title

['Miss.',
 'Master.',
 'Miss.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Col.',
 'Mrs.',
 'Mme.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Miss.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Miss.',
 'Mr.',
 'Miss.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Dr.',
 'Mrs.',
 'Mrs.',
 'Mrs.',
 'Miss.',
 'Major.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Master.',
 'Miss.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mrs.',
 'Miss.',
 'Miss.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Mrs.',
 'Mrs.',
 'Mr.',
 'Capt.',
 'Miss.',
 'Mrs.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mrs.',
 'Dr.',
 'Master.',
 'Mrs.',
 'Mr.',
 'Mrs.',
 'Mrs.',
 'Gordon,',
 'Gordon,',
 'Mr.',
 'Mrs.',
 'Miss.',
 'Miss.',
 'Miss.',
 'Mr.',
 'Mrs.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Miss.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Miss.',
 'Mr.',
 'Dr.',
 'Mr.',
 'Mrs.',
 'Miss.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Miss.',
 'Miss.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Col.',
 'Miss.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Mrs.',
 'Mrs.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Miss.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Miss.',
 'Dr.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Miss.',
 'Mrs.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Miss.',
 'Miss.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Mlle.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Dr.',
 'Miss.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Miss.',
 'Mr.',
 'Miss.',
 'Mr.',
 'y',
 'Mr.',
 'Miss.',
 'Mr.',
 'y',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'y',
 'y',
 'Miss.',
 'Major.',
 'Mr.',
 'Mrs.',
 'Jonkheer.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Mr.',
 'the',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Master.',
 'Miss.',
 'Miss.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mlle.',
 'Mr.',
 'Mrs.',
 'Miss.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Col.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mrs.',
 'Master.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mrs.',
 'Dr.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Mrs.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mrs.',
 'Miss.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Mrs.',
 'Mr.',
 'Don.',
 'der',
 'Mr.',
 'Miss.',
 'Mr.',
 'Mrs.',
 'Col.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Miss.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Rev.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Master.',
 'Miss.',
 'Miss.',
 'Mrs.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Miss.',
 'Mr.',
 'Mrs.',
 'Miss.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Rev.',
 'Mrs.',
 'Master.',
 'Mr.',
 'Mrs.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Rev.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Miss.',
 'Mrs.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Mrs.',
 'Mrs.',
 'Mrs.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Master.',
 'Mr.',
 'Mrs.',
 'Miss.',
 'Brito,',
 'Mr.',
 'Carlo,',
 'Carlo,',
 'Mr.',
 'Mr.',
 'Miss.',
 'Mrs.',
 'Mr.',
 'Master.',
 'Mr.',
 'Mrs.',
 'y',
 'y',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Master.',
 'Mrs.',
 'Mr.',
 'Miss.',
 'Rev.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Mrs.',
 'Miss.',
 'Miss.',
 'Mr.',
 'Mrs.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mrs.',
 'Mrs.',
 'Miss.',
 'Mr.',
 'Mrs.',
 'Rev.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Rev.',
 'Mr.',
 'Miss.',
 'Miss.',
 'Mr.',
 'Mrs.',
 'Miss.',
 'Miss.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Mrs.',
 'Mr.',
 'Master.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Rev.',
 'Dr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Master.',
 'Master.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'y',
 'Dr.',
 'y',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Rev.',
 'Miss.',
 'Miss.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Miss.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Ms.',
 'Mr.',
 'Master.',
 'Master.',
 'Mrs.',
 'Miss.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Miss.',
 'Miss.',
 'Miss.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Mrs.',
 'Miss.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Miss.',
 'Mrs.',
 'Miss.',
 'Mr.',
 'Mrs.',
 'Master.',
 'Miss.',
 'Mrs.',
 'Miss.',
 'Miss.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Miss.',
 'Mr.',
 'Master.',
 'Mr.',
 'Mrs.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Master.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Master.',
 'Miss.',
 'Miss.',
 'Miss.',
 'Miss.',
 'Miss.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Master.',
 'Master.',
 'Master.',
 'Master.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Khalil,',
 'Mr.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Miss.',
 'Miss.',
 'Miss.',
 'Mrs.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Mrs.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Master.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Master.',
 'Miss.',
 'Mr.',
 'Mrs.',
 'Miss.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Miss.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Miss.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Master.',
 'Master.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Master.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Messemaeker,',
 'Messemaeker,',
 'Mulder,',
 'Pelsmaeker,',
 'Master.',
 'Miss.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Miss.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Miss.',
 'Master.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Master.',
 'Master.',
 'Master.',
 'Miss.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Miss.',
 'Miss.',
 'Miss.',
 'Mr.',
 'Miss.',
 'Miss.',
 'Miss.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Shawah,',
 'Mr.',
 'Miss.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Palmquist,',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Master.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Master.',
 'Miss.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Mrs.',
 'Miss.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Master.',
 'Miss.',
 'Miss.',
 'Miss.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Miss.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Miss.',
 'Miss.',
 'Mr.',
 'Mr.',
 'Mr.',
 'Mrs.',
 'Mr.',
 'Miss.',
 ...]

In [ ]:
titan['title_1']=titan['name'].str.split().str[1].str.strip('.')  # removeing this  ' .', to title output so,it's clear output.

In [ ]:
titan['title_1']

0         Miss
1       Master
2         Miss
3           Mr
4          Mrs
         ...
1304      Miss
1305      Miss
1306        Mr
1307        Mr
1308        Mr
Name: title_1, Length: 1309, dtype: object

In [ ]:
# Pivot table..
# it also none as power house of pandas
# use:it is use apply multipal aggregate function on multipal columns's at the same type.

# syntax:
#       var.pivot_table(values=['col_1','col_2'......],
#                        index='categorical_col',
#                        aggfunc=['fname_1','fname_2',......])

In [ ]:
wine=pd.read_csv(r"C:\Users\Vinay Babu\Downloads\Data-Analysis-Datasets-main\Data-Analysis-Datasets-main\Datasets-Practice\winequalityN.csv")

In [ ]:
wine.head()

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,white,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,white,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [ ]:
wine.columns

Index(['type', 'fixed acidity', 'volatile acidity', 'citric acid',
       'residual sugar', 'chlorides', 'free sulfur dioxide',
       'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol',
       'quality'],
      dtype='str')

In [ ]:
wine.pivot_table(values=['pH','alcohol','quality'],
                 index='type',
                 aggfunc=['min','max','mean'])

          min                   max                     mean            \
      alcohol    pH quality alcohol    pH quality    alcohol        pH
type
red       8.4  2.74       3    14.9  4.01       8  10.422983  3.310864
white     8.0  2.72       3    14.2  3.82       9  10.514267  3.188203


        quality
type
red    5.636023
white  5.877909

In [ ]:
wine['alcohol'].min()

np.float64(8.0)

Date Range Function
1. pd.to_datetime(var['col_name'])
2. pd.date_range() => It will create the dates between specified limits.

Syntax:- 
        pd.date_range(start='DD/MM/YYYY',
                      end= 'DD/MM/YYYY',
                      freq='D')

In [32]:
pd.date_range(start='15/11/2019',
              end='5/9/2020',
              freq='D')  # we will apply to 2D,3D,W,W-any day-like W-mon,

DatetimeIndex(['2019-11-15', '2019-11-16', '2019-11-17', '2019-11-18',
               '2019-11-19', '2019-11-20', '2019-11-21', '2019-11-22',
               '2019-11-23', '2019-11-24',
               ...
               '2020-04-30', '2020-05-01', '2020-05-02', '2020-05-03',
               '2020-05-04', '2020-05-05', '2020-05-06', '2020-05-07',
               '2020-05-08', '2020-05-09'],
              dtype='datetime64[us]', length=177, freq='D')

D =
2D =
3D =
W  =
W - WEEK NAME =
B =
MS =
ME =
YS - FEB =
YE =

In [31]:
pd.date_range(start='15/11/2019',
              end='5/9/2020',
              freq='ME')  # B this break the starday and sunday

DatetimeIndex(['2019-11-30', '2019-12-31', '2020-01-31', '2020-02-29',
               '2020-03-31', '2020-04-30'],
              dtype='datetime64[us]', freq='ME')

In [30]:
pd.date_range(start='15/11/2019',
              end='5/9/2020',
              freq='ME')

DatetimeIndex(['2019-11-30', '2019-12-31', '2020-01-31', '2020-02-29',
               '2020-03-31', '2020-04-30'],
              dtype='datetime64[us]', freq='ME')

In [35]:
pd.date_range(start='15/11/2019',
              end='5/9/2020',
              freq='YS-FEB')

DatetimeIndex(['2020-02-01'], dtype='datetime64[us]', freq='YS-FEB')

In [41]:
amz=pd.read_csv(r'C:\Users\Vinay Babu\Downloads\Data-Analysis-Datasets-main\Data-Analysis-Datasets-main\Datasets-Practice\amazon_fires.csv',encoding='ISO-8859-1')

In [ ]:
# var['col_name'].dt.year 
#                   day 
#                   month

In [43]:
amz['new_date']=pd.date_range(start='1/2/2012',periods=len(amz))

In [ ]:
amz

In [ ]:
amz['new_date']

In [ ]:
amz['new_date'].dt.year

0       2012
1       2012
2       2012
3       2012
4       2012
        ...
6449    2029
6450    2029
6451    2029
6452    2029
6453    2029
Name: new_date, Length: 6454, dtype: int32